// calculator-angular/src/app/keyboard/keyboard.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-keyboard',
  standalone: true,
  imports: [],
  templateUrl: './keyboard.component.html',
  styleUrl: './keyboard.component.css'
})
export class KeyboardComponent {
  onPress(c: string, clear = false) {
    console.log("onPress clicked")
  }

  onCalculate() {
    console.log("onCalculate clicked")
  }
}

<!-- <div class='calculator-keyboard'> -->
<button class='grid-item-operator' (click)="onPress('+')">+</button>
<button class='grid-item-operator' (click)="onPress('-')">-</button>
<button class='grid-item-operator' (click)="onPress('*')">*</button>
<button class='grid-item-operator' (click)="onPress('/')">/</button>
<button class='grid-item-number' (click)="onPress('7')">7</button>
<button class='grid-item-number' (click)="onPress('8')">8</button>
<button class='grid-item-number' (click)="onPress('9')">9</button>
<button class='grid-item-calc' (click)="onCalculate()">=</button>
<button class='grid-item-number' (click)="onPress('4')">4</button>
<button class='grid-item-number' (click)="onPress('5')">5</button>
<button class='grid-item-number' (click)="onPress('6')">6</button>
<button class='grid-item-number' (click)="onPress('1')">1</button>
<button class='grid-item-number' (click)="onPress('2')">2</button>
<button class='grid-item-number' (click)="onPress('3')">3</button>
<button class='grid-item-number' (click)="onPress('', true)">C</button>
<button class='grid-item-number' (click)="onPress('0')">0</button>
<button class='grid-item-number'>.</button>
<!-- </div> -->

// calculator-react/src/components/Keyboard/Keyboard.tsx
import './Keyboard.css'

interface IKeyboard {
  onPress: (updated: string, clear?: boolean) => void;
  onCalculate: () => void
}
const Keyboard = ({ onCalculate, onPress }: IKeyboard) => {

  return (
    <div className='calculator-keyboard'>
      <button className='grid-item-operator' onClick={() => onPress('+')}>+</button>
      <button className='grid-item-operator' onClick={() => onPress('-')}>-</button>
      <button className='grid-item-operator' onClick={() => onPress('*')}>*</button>
      <button className='grid-item-operator' onClick={() => onPress('/')}>/</button>
      <button className='grid-item-number' onClick={() => onPress('7')}>7</button>
      <button className='grid-item-number' onClick={() => onPress('8')}>8</button>
      <button className='grid-item-number' onClick={() => onPress('9')}>9</button>
      <button className='grid-item-calc' onClick={() => onCalculate()}>=</button>
      <button className='grid-item-number' onClick={() => onPress('4')}>4</button>
      <button className='grid-item-number' onClick={() => onPress('5')}>5</button>
      <button className='grid-item-number' onClick={() => onPress('6')}>6</button>
      <button className='grid-item-number' onClick={() => onPress('1')}>1</button>
      <button className='grid-item-number' onClick={() => onPress('2')}>2</button>
      <button className='grid-item-number' onClick={() => onPress('3')}>3</button>
      <button className='grid-item-number' onClick={() => onPress('', true)}>C</button>
      <button className='grid-item-number' onClick={() => onPress('0')}>0</button>
      <button className='grid-item-number'>.</button>
    </div >
  )
}

export default Keyboard;
